import { ourFileRouter } from '@/app/(app)/api/uploadthing/core';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import type { Metadata } from 'next';
import { connection } from 'next/server';
import { Suspense } from 'react';
import { extractRouterConfig } from 'uploadthing/server';

import './globals.css';

export const metadata: Metadata = {
  title: 'Template Mini App',
  description: 'Generated by create next app',
};

async function UploadThingSSR() {
  await connection();
  return (
    <NextSSRPlugin
      /**
       * Same data as fetching `/api/uploadthing`; avoids leaking extra server info.
       */
      routerConfig={extractRouterConfig(ourFileRouter)}
    />
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <UploadThingSSR />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
